<?php

return array(
  'PROJECT_CREATE'   => 0,
  'PROJECT_COMPLETE' => 1,
  'PROJECT_CANCELED' => 2,

  'TASK_CREATE'             => 0,
  'TASK_SUBMIT_SUPERIOR'    => 1,
  'TASK_APPROVAL_SUPERIOR'  => 2,
  'TASK_SUBMIT_PARTNER'     => 3,
  'TASK_APPROVAL_PARTNER'   => 4,
  'ORDER_SUBMIT_SUPERIOR'   => 5,
  'ORDER_APPROVAL_SUPERIOR' => 6,
  'ORDER_SUBMIT_PARTNER'    => 7,
  'ORDER_APPROVAL_PARTNER'  => 8,
  'WORKING'                 => 9,
  'DELIVERY_PARTNER'        => 10,
  'ACCEPTANCE'              => 11,
  'INVOICE_DRAFT_CREATE'    => 12,
  'INVOICE_CREATE'          => 13,
  'SUBMIT_STAFF'            => 14,
  'SUBMIT_ACCOUNTING'       => 15,
  'APPROVAL_ACCOUNTING'     => 16,
  'COMPLETE_STAFF'          => 17,
  'TASK_CANCELED'           => 18,

  'TASK_STATUS_LIST' => [
    '下書き',
    'タスク上長確認中',
    'タスクパートナー依頼前',
    'タスクパートナー確認中',
    '発注書作成前',
    '発注書上長確認中',
    '発注書パートナー依頼前',
    '発注書パートナー確認中',
    '作業前',
    '作業中',
    '検品中',
    '請求書作成前',
    '請求書下書き',
    '請求書担当者確認前',
    '請求書担当者確認中',
    '請求書経理提出',
    '請求書経理承認済み',
    '完了',
    'キャンセル',
  ],

  'FREE_TAX' => 0,
  'REDUCED_EIGHT_TAX' => 0.08,
  'TEN_TAX' => 0.1,
);