<?php

return array(
    'ASK_TO_SUPERIOR_FROM_COMPANY_USER' => [
        'TASK_APPROVAL_SUPERIOR',
        'ORDER_APPROVAL_SUPERIOR',
    ],

    'ASK_TO_ACCOUNTING_FROM_COMPANY_USER' => [
        'INVOICE_CREATE',
    ],

    'ASK_TO_PARTNER_FROM_COMPANY_USER' => [
        'TASK_APPROVAL_SUPERIOR',
        'SUBMIT_STAFF',
    ],

    'APPROVED_SUPERIOR' => [
        'TASK_SUBMIT_SUPERIOR',
        'ORDER_SUBMIT_SUPERIOR',
    ],

    'APPROVED_ACCOUNTING' => [
        'SUBMIT_ACCOUNTING',
    ],
);
